services:
  waterfowlenergy:
    container_name: waterfowlenergy
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 5g
    ports:
      - '9001:9000'
    volumes:
      - ./WaterfowlEnergyDuckdb_voila.ipynb:/app/WaterfowlEnergyDuckdb_voila.ipynb
      - ./voila.json:/app/voila.json
    command: voila --port 9000 --Voila.ip='0.0.0.0' --no-browser --MappingKernelManager.cull_idle_timeout=600 --MappingKernelManager.cull_interval=120 --MappingKernelManager.cull_busy=False WaterfowlEnergyDuckdb_voila.ipynb
