version: "3.8"
services:
  waterfowlenergy:
    container_name: waterfowlenergy
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 7168M
    ports:
      - '9001:9000'
    volumes:
      - ./WaterfowlEnergyDuckdb_voila.ipynb:/app/WaterfowlEnergyDuckdb_voila.ipynb
      - ./voila.json:/app/voila.json
    command: voila --port 9000 --Voila.ip='0.0.0.0' --no-browser WaterfowlEnergyDuckdb_voila.ipynb
